# Generated by Django 6.0.5 on 2026-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
