# Generated by Django 6.0.5 on 2026-06-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizzamodel_price_pizzamodel_size'),
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.pizzashopmodel'),
            preserve_default=False,
        ),
    ]
