# Generated by Django 6.0.5 on 2026-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashopmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
