# Generated by Django 6.0.5 on 2026-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
